name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install HTML Tidy
        run: sudo apt-get update && sudo apt-get install -y tidy

      - name: Validate HTML
        run: |
          echo "<!DOCTYPE html>" > temp.html
          cat index.html >> temp.html
          tidy -q -e temp.html
          rm temp.html

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
